"adagio"= """pyarrow="16.0"\n"""
"advertools"= """pyarrow="16.0"\n"""
"alchemlyb"= """pyarrow="16.0"\n"""
"apache-airflow-providers-apache-beam"= """pyarrow="16.0"\n"""
"apache-airflow-providers-databricks"= """pyarrow="16.0"\n"""
"apache-airflow-providers-snowflake"= """pyarrow="16.0"\n"""
"apache-beam"= """pyarrow="16.0"\n"""
#"apache-flink"= """pyarrow="16.0"\n"""
"apache-superset"= """pyarrow="16.0"\n"""
"arboreto"= """pyarrow="16.0"\n"""
"arize"= """pyarrow="16.0"\n"""
"arthurai"= """pyarrow="16.0"\n"""
"astro-sdk-python"= """pyarrow="16.0"\n"""
"autoawq"= """pyarrow="16.0"\n"""
"autofaiss"= """pyarrow="16.0"\n"""
"autogluon"= """pyarrow="16.0"\n"""
"auto-gptq"= """pyarrow="16.0"\n"""
"autotrain-advanced"= """pyarrow="16.0"\n"""
"awswrangler"= """pyarrow="16.0"\n"""
"azureml-dataset-runtime"= """pyarrow="16.0"\n"""
"azureml-defaults"= """pyarrow="16.0"\n"""
"azureml-featurestore"= """pyarrow="16.0"\n"""
"backends-matrix"= """pyarrow="16.0"\n"""
"beam-nuggets"= """pyarrow="16.0"\n"""
"bgen-reader"= """pyarrow="16.0"\n"""
"bigquery"= """pyarrow="16.0"\npandas=">=1.6"\n"""
"blackboxauditing"= 'gast="<0.6"\ncatboost="<1.2"\n'
"brainglobe-napari-io"= """pyarrow="16.0"\n"""
"brainreg"= """pyarrow="16.0"\n"""
"caveclient"= """pyarrow="16.0"\n"""
"coffea"= """pyarrow="16.0"\n"""
"ctxcore"= """pyarrow="16.0"\n"""
"d3m"= """numpy=">1.26"\n"""
"dagster-gcp"= """pyarrow="16.0"\n"""
"daipe-core"= """pandas=">=1.6\n"""
"darts"= """pyarrow="16.0"\n"""
"dask-expr"= """pyarrow="16.0"\n"""
"dask-geopandas"= """pyarrow="16.0"\n"""
"dask-image"= """pyarrow="16.0"\n"""
"dask-ml"= """pyarrow="16.0"\n"""
"dask-sql"= """pyarrow="16.0"\n"""
"databricks-connect"= """pyarrow="16.0"\n"""
"databricks-sql-connector"= """pyarrow="16.0"\n"""
"datacompy"= """pyarrow="16.0"\n"""
"dataengine"= """pyarrow="16.0"\n"""
"datafusion"= """pyarrow="16.0"\n"""
"datapane"= """pyarrow="16.0"\n"""
"datasets"= """pyarrow="16.0"\n"""
"db-dtypes"= """pyarrow="16.0"\n"""
"dbt-bigquery"= """pyarrow="16.0"\n"""
"dbt-databricks"= """pyarrow="16.0"\n"""
"deltalake"= """pyarrow="16.0"\n"""
"delta-sharing"= """pyarrow="16.0"\n"""
"dspy-ai"= """pyarrow="16.0"\n"""
"dvc-hdfs"= """pyarrow="16.0"\n"""
"embedding-reader"= """pyarrow="16.0"\n"""
"equilibrator-api"= """pyarrow="16.0"\n"""
"evaluate"= """pyarrow="16.0"\n"""
"evidently"= """pyarrow="16.0"\n"""
"extra-streamlit-components"= """pyarrow="16.0"\n"""
"feast"= """pyarrow="16.0"\n"""
"feather-format"= """pyarrow="16.0"\n"""
"fiddler-client"= """pyarrow="16.0"\n"""
"flytekit"= """pyarrow="16.0"\n"""
"fugue"= """pyarrow="16.0"\n"""
"fugue-sql-antlr"= """pyarrow="16.0"\n"""
"geetools"= """pyarrow="16.0"\n"""
"graphdatascience"= """pyarrow="16.0"\n"""
"gtfparse"= """pyarrow="16.0"\n"""
"h3ronpy"= """pyarrow="16.0"\n"""
"handyspark"= """pyarrow="16.0"\n"""
"hydralit"= """pyarrow="16.0"\n"""
"ibis-framework"= """pyarrow="16.0"\n"""
"ibllib"= """pyarrow="16.0"\n"""
"image-reward"= """pyarrow="16.0"\n"""
"imio"= """pyarrow="16.0"\n"""
"influxdb3-python"= """pyarrow="16.0"\n"""
"intake-esm"= """pyarrow="16.0"\n"""
"intake-parquet"= """pyarrow="16.0"\n"""
"json2parquet"= """pyarrow="16.0"\n"""
"koalas"= """pyarrow="16.0"\n"""
"kss"= """pyarrow="16.0"\n"""
"lancedb"= """pyarrow="16.0"\n"""
"limix"= """pyarrow="16.0"\n"""
"lm-eval"= """pyarrow="16.0"\n"""
"lyrebird"= """frozenlist=">1.4"\ncryptography=">39"\nyarl = ">1.9"\n"""
"markdownlit"= """pyarrow="16.0"\n"""
"mbf-heatmap"= """pyarrow="16.0"\n"""
"minichain"= """pyarrow="16.0"\n"""
"mlflow"= """pyarrow="16.0"\n"""
"mlflow-watsonml"= """pyarrow="16.0"\n"""
"mlserver-mlflow"= """pyarrow="16.0"\n"""
"mltable"= """pyarrow="16.0"\n"""
"modelscope"= """pyarrow="16.0"\n"""
"mteb"= """pyarrow="16.0"\n"""
"nglui"= """pyarrow="16.0"\n"""
"nlp"= """pyarrow="16.0"\n"""
"nteract-scrapbook"= """pyarrow="16.0"\n"""
"openllm"= """pyarrow="16.0"\n"""
"openml"= """pyarrow="16.0"\n"""
"optimum"= """pyarrow="16.0"\n"""
"oremda-core"= """pyarrow="16.0"\n"""
"outlines"= """pyarrow="16.0"\n"""
"paddlenlp"= """pyarrow="16.0"\n"""
"pandas-gbq"= """pyarrow="16.0"\n"""
"pandas-plink"= """pyarrow="16.0"\n"""
"pandas-read-xml"= """pyarrow="16.0"\n"""
"pantab"= """pyarrow="16.0"\n"""
"parquet-tools"= """pyarrow="16.0"\n"""
"petab"= """pyarrow="16.0"\n"""
"petastorm"= """pyarrow="16.0"\n"""
"pod5"= """pyarrow="16.0"\n"""
"ppscore"= """pandas=">=1.6\n"""
"pyarrowfs-adlgen2"= """pyarrow="16.0"\n"""
"pyarrow"= """pyarrow="16.0"\n"""
"pyensembl"= """pyarrow="16.0"\n"""
"pygwalker"= """pyarrow="16.0"\n"""
"pylance"= """pyarrow="16.0"\n"""
"pynhd"= """pyarrow="16.0"\n"""
"pyodps"= """pyarrow="16.0"\n"""
"pyscenic"= """pyarrow="16.0"\n"""
"pyserini"= """pyarrow="16.0"\n"""
"qcodes-contrib-drivers"= """pyarrow="16.0"\n"""
"qcodes-loop"= """pyarrow="16.0"\n"""
"qcodes"= """pyarrow="16.0"\n"""
"qpd"= """pyarrow="16.0"\n"""
"quilt"= """pyarrow="16.0"\n"""
"ragas"= """pyarrow="16.0"\n"""
"rerun-sdk"= """pyarrow="16.0"\n"""
"rikai"= """pyarrow="16.0"\n"""
"scrapbook"= """pyarrow="16.0"\n"""
"sdatabricks-connect"= """pyarrow="16.0"\n"""
"servicex"= """pyarrow="16.0"\n"""
"setfit"= """pyarrow="16.0"\n"""
"simpletransformers"= """pyarrow="16.0"\n"""
"snapflow"= """pyarrow="16.0"\n"""
"sqlalchemy-databricks"= """pyarrow="16.0"\n"""
"squidpy"= """pyarrow="16.0"\n"""
"starfile"= """pyarrow="16.0"\n"""
"statsforecast"= """pyarrow="16.0"\n"""
"stheno"= """pyarrow="16.0"\n"""
"storey"= """pyarrow="16.0"\n"""
"stqdm"= """pyarrow="16.0"\n"""
"streamlit-ace"= """pyarrow="16.0"\n"""
"streamlit-aggrid"= """pyarrow="16.0"\n"""
"streamlit-authenticator"= """pyarrow="16.0"\n"""
"streamlit-camera-input-live"= """pyarrow="16.0"\n"""
"streamlit-card"= """pyarrow="16.0"\n"""
"streamlit-cookies-controller"= """pyarrow="16.0"\n"""
"streamlit-embedcode"= """pyarrow="16.0"\n"""
"streamlit-extras"= """pyarrow="16.0"\n"""
"streamlit-faker"= """pyarrow="16.0"\n"""
"streamlit-image-coordinates"= """pyarrow="16.0"\n"""
"streamlit-keyup"= """pyarrow="16.0"\n"""
"streamlit-option-menu"= """pyarrow="16.0"\n"""
"streamlit-profiler"= """pyarrow="16.0"\n"""
"streamlit"= """pyarrow="16.0"\n"""
"streamlit-toggle-switch"= """pyarrow="16.0"\n"""
"streamlit-vertical-slider"= """pyarrow="16.0"\n"""
"swifter"= """pyarrow="16.0"\n"""
"tdda"= """pyarrow="16.0"\n"""
"tensor2tensor"= """pyarrow="16.0"\n"""
"tensorflow-datasets"= """pyarrow="16.0"\n"""
"tensorflow-privacy"= """pyarrow="16.0"\n"""
"text2vec"= """pyarrow="16.0"\n"""
"textual-fastdatatable"= """pyarrow="16.0"\n"""
"tfds-nightly"= """pyarrow="16.0"\n"""
"tf-models-official"= """pyarrow="16.0"\n"""
"tfx"= """pyarrow="16.0"\n"""
"tikzplotlib"= """matplotlib="<=3.7"\n"""
"triad"= """pyarrow="16.0"\n"""
"trl"= """pyarrow="16.0"\n"""
"vaex-core"= """pyarrow="16.0"\n"""
"vaex"= """pyarrow="16.0"\n"""
"varcode"= """pyarrow="16.0"\n"""
"varz"= """pyarrow="16.0"\n"""
"vllm"= """pyarrow="16.0"\n"""
"wbml"= """pyarrow="16.0"\n"""
"weave"= """pyarrow="16.0"\n"""
"xbbg"= """pyarrow="16.0"\n"""
"xclim"= """pyarrow="16.0"\n"""
"qscintilla"= """pyqt5-qt5 = "=5.15.2"\n"""
"genice" = """numpy="<2"\n"""
"bob-measure" = """numba="<0.60"\n"""
"networkit" = """numpy="<2"\n"""
"pymatgen"= """numpy="<2"\n"""
"rembg-2.0.57" = """numpy="2.0.0"\n""" # numba 0.60 does not compile with numpy 2.0.1 https://github.com/numba/numba/issues/9687
